# Generated by Django 3.2 on 2023-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('password', models.TextField(max_length=14, verbose_name='Пароль')),
                ('name', models.TextField(max_length=256, verbose_name='Имя и фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
